server:
  port: ${APP_PORT:8094}
  servlet:
    context-path: /aurora
import:
  aurora:
    import_data_from: local
    import_data_by_date: 2021-11-10
    import_data_from_timestamp: 20211111183528
    simulate_as_today: true
    local_data_dir: c:/Project/aurora/maggraphs/temp
    http_data_url: https://www2.irf.se/maggraphs/rt.txt
    #url: https://www2.irf.se/maggraphs/rt.txt
    temporary_directory: c:/Project/aurora/maggraphs/temp/
    #cron_rt_load:
    cron_rt_load: 1 */5 * * * ?
    cron_clear_temporary_directory: ${SCHEDULER_CRON_CLEAR_TMP_DIR:}
  chunk-size: 100
  retry-count: 5
spring:
  main:
    allow-bean-definition-overriding: true
  batch:
    schema: classpath:batch/schema-postgresql.sql
    initialize-schema: always
    job:
      enabled: false
  datasource:
    driverClassName: org.postgresql.Driver
    url: ${DB_URL:jdbc:postgresql://localhost:5432/interstorage?serverTimezone=Europe/Moscow}
    username: ${DB_USERNAME:user}
    password: ${DB_PASSWORD:password}
    testOnBorrow: true
    validationQuery: SELECT 1
    hikari:
      maximumPoolSize: 50
      idleTimeout: 600000
      connectionTimeout: 100000
      validationTimeout: 5000
      maxLifetime: 1800000
  jackson:
    date-format: yyyy-MM-dd'T'HH:mm:ss.SSS'Z'
    serialization:
      FAIL_ON_EMPTY_BEANS: false
